name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names medilab-2 --region us-east-1 || \
          aws ecr create-repository --repository-name medilab-2 --region us-east-1

      - name: Build, tag, and push Docker image to ECR (Automated)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: medilab-2
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Show ECR Image URL
        run: |
          echo "✅ Image successfully pushed!"
          echo "Image URI: 780139020397.dkr.ecr.us-east-1.amazonaws.com/medilab-2:latest"

      - name: Login to Amazon ECR (Manual Login Test)
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 780139020397.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Image to ECR (Manual)
        run: |
          docker build -t medilab-2 .:v1
          docker tag medilab-2:latest 780139020397.dkr.ecr.us-east-1.amazonaws.com/medilab-2:v1
          docker push 780139020397.dkr.ecr.us-east-1.amazonaws.com/medilab-2:v1
